void LoadCharacterInfo(gentity_t * ent);
void LevelCheck(int charID);
void Cmd_ListCharacters_F(gentity_t * ent);
void Cmd_Character_F(gentity_t * ent);
void Cmd_CreateCharacter_F(gentity_t * ent);
void Cmd_CharacterInfo_F(gentity_t * ent);
void Cmd_GiveCredits_F(gentity_t * ent);
void Cmd_FactionInfo_F(gentity_t * ent);
void Cmd_FactionWithdraw_F(gentity_t * ent);
void Cmd_FactionDeposit_F(gentity_t * ent);
void Cmd_ListFactions_F(gentity_t * ent);
void Cmd_CheckInventory_F(gentity_t * ent);
void Cmd_Inventory_F(gentity_t * ent);
void Cmd_EditCharacter_F(gentity_t * ent);
void Cmd_Bounty_F(gentity_t * ent);
void Cmd_CharName_F(gentity_t * ent);
void Cmd_Radio_F(gentity_t *ent);
void Cmd_ForceBondMessage_F(gentity_t *ent);
void Cmd_Faction_F(gentity_t * ent);
void Cmd_SetFactionRank_F(gentity_t * ent);
void Cmd_Frequency_F(gentity_t *ent);
void Cmd_AddFrequency_F(gentity_t *ent);
void Cmd_FactionLeave_F(gentity_t *ent);
void Cmd_FactionInvite_F(gentity_t *ent);
void Cmd_FactionInviteAccept_F(gentity_t *ent);
void Cmd_FactionInviteDecline_F(gentity_t *ent);
