void Cmd_info_F(gentity_t *ent);
void Cmd_aminfo_F(gentity_t *ent);
void Cmd_eminfo_F(gentity_t *ent);
void Cmd_ListAdmins_F(gentity_t *ent);
void Cmd_ToggleChat_F(gentity_t * ent);
void Cmd_TrainingSaber_F(gentity_t *ent);
void Cmd_Hologram_F(gentity_t *ent);
void Cmd_AutoWalk_F(gentity_t *ent);
void InitializeSQL(void);
void Cmd_Roll_F(gentity_t *ent);
void Cmd_StunMode_F(gentity_t * ent);
void Cmd_OrderNPC_f(gentity_t *ent);